Repository IEAWindSystems/windIO, pull requests merged in 2025-03, with the labels that each got.

#80 move to ultra restrictive schema
  windIO/__init__.py
  windIO/examples/plant/plant_energy_site/IEA37_case_study_3_energy_site.yaml
  windIO/schemas/plant/common.yaml
  windIO/schemas/plant/energy_resource.yaml
  windIO/schemas/plant/site.yaml
  windIO/schemas/plant/wind_farm.yaml
  windIO/schemas/turbine/IEAontology_schema.yaml
Labels: python-library

#105 Add schema rendering to the docs
  .github/workflows/gh-pages.yaml
  .gitignore
  docs/Makefile
  docs/_static/plant_schema.html
  docs/_static/turbine_schema.html
  docs/conf.py
  docs/index.rst
  docs/jsfh_config.json
  docs/jsfh_template/Readme.md
  docs/jsfh_template/badge_type.html
  docs/jsfh_template/base.html
  docs/jsfh_template/breadcrumbs.html
  docs/jsfh_template/config_schema.json
  docs/jsfh_template/content.html
  docs/jsfh_template/macro_restriction.html
  docs/jsfh_template/section_array.html
  docs/jsfh_template/section_conditional_subschema.html
  docs/jsfh_template/section_description.html
  docs/jsfh_template/section_examples.html
  docs/jsfh_template/section_not.html
  docs/jsfh_template/section_properties.html
  docs/jsfh_template/section_undocumented_required_properties.html
  docs/jsfh_template/tabbed_section.html
  docs/schema_export.py
  docs/source/airfoils.rst
  docs/source/assembly.rst
  docs/source/blade.rst
  docs/source/components.rst
  docs/source/control.rst
  docs/source/costs.rst
  docs/source/environment.rst
  docs/source/floating.rst
  docs/source/hub.rst
  docs/source/materials.rst
  docs/source/monopile.rst
  docs/source/mooring.rst
  docs/source/nacelle.rst
  docs/source/plant.rst
  docs/source/plant_energy_resource.rst
  docs/source/plant_energy_site.rst
  docs/source/plant_schema.rst
  docs/source/tower.rst
  docs/source/turbine.rst
  docs/source/turbine_schema.rst
  docs/source/wind_energy_system.rst
  docs/source/wind_farm.rst
  pyproject.toml
  windIO/schemas/plant/wind_energy_system.yaml
  windIO/schemas/turbine/IEAontology_schema.yaml
Labels: documentation

#87 Upgrade turbine schema
  .gitignore
  test/turbine/test_turbine.py
  test/turbine/v1p0/IEA-15-240-RWT.yaml
  test/turbine/v1p0/IEA-15-240-RWT_VolturnUS-S.yaml
  windIO/__init__.py
  windIO/converters/windIO2windIO.py
  windIO/examples/turbine/IEA-15-240-RWT.yaml
  windIO/examples/turbine/IEA-15-240-RWT_VolturnUS-S.yaml
  windIO/schemas/turbine/turbine_schema.yaml
Labels: turbine, schema
